[build]
  command = "CI='' npm install && npm run build
"
  publish = "build"

[context.production.environment]
  NODE_VERSION = "18.20.0"
  NPM_VERSION = "9.5.0"
  CI = "true"
  NODE_OPTIONS = "--openssl-legacy-provider"
