[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  NODE_VERSION = "18.20.0" # Specify Node.js 18 or later
  NPM_VERSION = "9.5.0"    # Optional but recommended
  CI = "true"
